CREATE TABLE IF NOT EXISTS experiences (
    id BIGINT PRIMARY KEY,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT,
    level VARCHAR(80),
    duration VARCHAR(60),
    price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    image VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    hours TEXT NOT NULL,
    hour_messages TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS customer_users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    phone VARCHAR(60) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    password VARCHAR(180) NOT NULL,
    role VARCHAR(40) NOT NULL DEFAULT 'CUSTOMER',
    bonuses INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE customer_users ADD COLUMN IF NOT EXISTS role VARCHAR(40) NOT NULL DEFAULT 'CUSTOMER';

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT PRIMARY KEY,
    user_id BIGINT REFERENCES customer_users(id) ON DELETE SET NULL,
    experience_id BIGINT REFERENCES experiences(id) ON DELETE SET NULL,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(180) NOT NULL,
    date_label VARCHAR(180) NOT NULL,
    date_key DATE NOT NULL,
    hour VARCHAR(5) NOT NULL,
    payment VARCHAR(80) NOT NULL,
    customer_name VARCHAR(160) NOT NULL,
    phone VARCHAR(60) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
